import numpy as mynp
myndarray = mynp.arange(9)
print(f'myndarray is: {myndarray}')
print(f'Array dimensions is: {myndarray.ndim}')
print(f'Data type of elements of array is :  {myndarray.dtype}')
print(f'Array size is : {myndarray.size}')
print(f'Array shape is : {myndarray.shape}')
print('-'*50)
myndarray1 = mynp.arange(1,9)
print(f'myndarray is: {myndarray1}')
print(f'Array dimensions is: {myndarray1.ndim}')
print(f'Data type of elements of array is :  {myndarray1.dtype}')
print(f'Array size is : {myndarray1.size}')
print(f'Array shape is : {myndarray1.shape}')
print('-'*50)
myndarray2 = mynp.arange(1,9,2)
print(f'myndarray is: {myndarray2}')
print(f'Array dimensions is: {myndarray2.ndim}')
print(f'Data type of elements of array is :  {myndarray2.dtype}')
print(f'Array size is : {myndarray2.size}')
print(f'Array shape is : {myndarray2.shape}')
print('-'*50)
myndarray3 = mynp.arange(1,9,3,dtype=float)
print(f'myndarray is: {myndarray3}')
print(f'Array dimensions is: {myndarray3.ndim}')
print(f'Data type of elements of array is :  {myndarray3.dtype}')
print(f'Array size is : {myndarray3.size}')
print(f'Array shape is : {myndarray3.shape}')
